In [8]:
import torch

In [11]:
#To check if CUDA is available in system or not
torch.cuda.is_available()

True

## Torch Tensors

In [13]:
#This is a 1-D tensor
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [31]:
#This is a 2-D tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [15]:
#The size of the tensor
print(a.size())
print(b.size())
print(a.shape)
print(b.shape)

torch.Size([3])
torch.Size([3, 3])
torch.Size([3])
torch.Size([3, 3])


In [18]:
#Define a float tensor
c = torch.FloatTensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]])
print(c)
print(c.dtype)

#c = torch.tensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]], dtype=torch.float)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [6., 7., 8.]])
torch.float32


In [19]:
#Define double tensor
d = torch.DoubleTensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]])
print(d)
print(d.dtype)
# d= torch.tensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]], dtype=torch.double)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [6., 7., 8.]], dtype=torch.float64)
torch.float64


In [22]:
#Finding mean and standard deviation of a tensor
print("Mean : ", c.mean())
print("Std. Dev : ", c.std())

Mean :  tensor(4.4444)
Std. Dev :  tensor(2.2973)


In [33]:
#Reshaping a tensor
#NOTE : The number of elements in the reshaped tensor should be same as the original tensor
#NOTE : If one of the dimension is -1, it is automatically calculated
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

#Assign b a new shape
b = b.view(-1, 1)
print(b)
print(b.shape)

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
torch.Size([12, 1])
