In [1]:
import torch

In [2]:
#To check if CUDA is available in system or not
torch.cuda.is_available()

False

## Torch Tensors

In [3]:
#This is a 1-D tensor
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [4]:
#This is a 2-D tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [5]:
#The size of the tensor
print(a.size())
print(b.size())
print(a.shape)
print(b.shape)

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [6]:
#Define a float tensor
c = torch.FloatTensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]])
print(c)
print(c.dtype)

#c = torch.tensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]], dtype=torch.float)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [6., 7., 8.]])
torch.float32


In [7]:
#Define double tensor
d = torch.DoubleTensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]])
print(d)
print(d.dtype)
# d= torch.tensor([[2, 1, 4], [3, 5, 4], [6, 7, 8]], dtype=torch.double)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [6., 7., 8.]], dtype=torch.float64)
torch.float64


In [8]:
#Finding mean and standard deviation of a tensor
print("Mean : ", c.mean())
print("Std. Dev : ", c.std())

Mean :  tensor(4.4444)
Std. Dev :  tensor(2.2973)


In [9]:
#Reshaping a tensor
#NOTE : The number of elements in the reshaped tensor should be same as the original tensor
#NOTE : If one of the dimension is -1, it is automatically calculated
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

#Assign b a new shape
b = b.view(-1, 1)
print(b)
print(b.shape)

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
torch.Size([12, 1])


In [10]:
#Create a 3-D tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2, 3, 4)
print(three_dim, "\n")

#Reshape the 3-D tensor
print("Reshaped 3-D tensor : ")
print(three_dim.view(2, 12))
print(three_dim.view(2, -1))

tensor([[[-1.3240,  0.5863,  0.2825,  0.0371],
         [ 0.2998,  0.1817,  1.6659,  0.0408],
         [-0.1512, -0.3019, -0.9479,  1.6183]],

        [[ 0.3859,  0.5155,  0.7343, -0.3033],
         [-0.7734,  0.4085, -0.0281,  0.1297],
         [-0.9542, -1.7936, -1.1147, -0.4114]]]) 

Reshaped 3-D tensor : 
tensor([[-1.3240,  0.5863,  0.2825,  0.0371,  0.2998,  0.1817,  1.6659,  0.0408,
         -0.1512, -0.3019, -0.9479,  1.6183],
        [ 0.3859,  0.5155,  0.7343, -0.3033, -0.7734,  0.4085, -0.0281,  0.1297,
         -0.9542, -1.7936, -1.1147, -0.4114]])
tensor([[-1.3240,  0.5863,  0.2825,  0.0371,  0.2998,  0.1817,  1.6659,  0.0408,
         -0.1512, -0.3019, -0.9479,  1.6183],
        [ 0.3859,  0.5155,  0.7343, -0.3033, -0.7734,  0.4085, -0.0281,  0.1297,
         -0.9542, -1.7936, -1.1147, -0.4114]])


In [11]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4, 4)
print(r)

tensor([[0.4648, 0.1645, 0.0979, 0.9687],
        [0.9027, 0.8276, 0.9910, 0.0236],
        [0.8042, 0.2436, 0.6487, 0.7413],
        [0.5644, 0.0329, 0.4277, 0.6437]])


In [12]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
n = torch.randn(4, 4)
print(n)
print(n.dtype)

tensor([[-1.5429,  0.1855,  0.9377,  0.3345],
        [-1.0267, -0.8061,  0.9022,  0.5362],
        [ 1.5985,  0.0914, -0.0325, -0.1064],
        [ 0.0839, -1.3070, -0.6232,  0.5729]])
torch.float32


In [13]:
#Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)
print(in_array.dtype)

tensor([7, 7, 9, 6, 9])
torch.int64
